[package]
name = "fastchaos"
version = "0.1.0"
authors = ["Anicet Ebou <anicet.ebou@gmail.com>"]
edition = "2018"
description = "fastchaos encode, decode and analyze DNA sequence using integer Chaos Game Representation" 
homepage = "https://github.com/Ebedthan/fastchaos"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["bioinformatics", "DNA encoding", "chaos game representation"] 


[dependencies]
anyhow        = "1.0.40"
bio           = "0.39"
clap          = "2.33"
exitcode      = "1.1.2"
serde         = {version = "1.0", features = ["derive"]}
serde_json    = "1.0"

[profile.release]
opt-level       = 3
debug           = true
overflow-checks = false
lto             = 'thin'
panic           = 'abort'
incremental     = false

[[bin]]
name = "fastchaos"
path = "src/main.rs"
bench = false
